name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - name: Run Tests
        run: npm test

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./reports/

  build:
      name: Build Project
      runs-on: ubuntu-latest
    
      steps:
        - uses: actions/checkout@v3
    
        - uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'npm'
    
        - run: npm ci
    
        - run: npm run build
  
  send-email:
    name: Send Email Notification
    runs-on: ubuntu-latest
    needs: [run-unit-tests, build]

    steps:
      - name: Install mailutils
        run: sudo apt-get install -y mailutils

      - name: Send Email
        run: |
          if [ -z "${{ secrets.EMAIL_RECIPIENT }}" ]; then
            echo "Error: EMAIL_RECIPIENT is not set"
            exit 1
          fi
          echo "Pipeline Executado com Sucesso" | mail -s "Notificação de Pipeline" ${{ secrets.EMAIL_RECIPIENT }}

